export const ADD_FAVORITES = "ADD_FAVORITES";
export const REMOVE_FAVORITES = "REMOVE_FAVORITES";
export const SET_TITLE = "SET_TITLE";
export const FETCH_RECOMMENDATIONS = "FETCH_RECOMMENDATIONS";
export const FETCH_ANIME = "FETCH_ANIME";
export const FETCH_BY_ID = "FETCH_BY_ID";